### ISSUE TITLE
No functionality for exact phrase search?

### ISSUE THREAD

**Issue by swood-ecology** [juba/rwos#1]
I'm looking to search for an exact phrase and can't figure out the syntax. Searching with AND or SAME is straightforward:

```
sq <- wos_search(sid, "TS=(soil SAME quality)")
sq <- wos_search(sid, "TS=(soil AND quality)")
```

What I'd like to search is:

`sq <- wos_search(sid, "TS="soil quality" ")`

But that syntax doesn't work. I can't find a description of functionality to do that sort of exact phrase search in rwos.

**Comment by juba** [comment]
Well, each of the following commands should work : 

```r
sq <- wos_search(sid, 'TS="soil quality"')
sq <- wos_search(sid, "TS=\"soil quality\"")
```
Is it what you're trying to achieve ?

One strange thing is that these two expressions don't give the same number of results : 

```r
sq <- wos_search(sid, 'TS="soil quality"')
sq <- wos_search(sid, "TS='soil quality'")
```
So it seems that the WOS API doesn't deal with single and double quotes the same way...

**Comment by swood-ecology** [comment]
I had tried single quotes initially. What I found odd is that each of the three search terms below returns the _exact_ same number of results. I'd expect there'd be at least a small difference. 

```
> sh <- wos_search(sid, "TS=(soil SAME health)")
16367 records found
> sh <- wos_search(sid, "TS=(soil AND health)")
16367 records found
> sh <- wos_search(sid, "TS= 'soil health' ") 
16367 records found 
```
But your first two commands narrow those results by a factor of 3, which makes sense. Thanks. It might be helpful for others if you added some guidelines to your vignette about search syntax.

**Comment by juba** [comment]
Yep, that's a good idea. If only I could really understand how this API works...

**Comment by swood-ecology** [comment]
Also, I meant to point out that when I searched the same terms on the WOS website I got much different number of hits:

1. soil SAME health = 18,997
2. soil AND health = 18,997
3. "soil health" = 1,401

It was nice to see the first two give the same given that I was getting the same, although different, results from 

```
sh <- wos_search(sid, "TS=(soil SAME health)")
16367 records found
sh <- wos_search(sid, "TS=(soil AND health)")
16367 records found
```

I figured there were fewer hits through rwos because it was working with the lite API. Not quite sure what that is, but figured it restricts access somehow. What I couldn't sort out was why there were fewer hits for "soil health" on the web vs `wos_search(sid, 'TS="soil quality"')` through rwos. 

Any thoughts? For a thorough literature search do you think it'd be "safer" now to download the reference lists through the web?

**Comment by juba** [comment]
The difference in results is due to the fact that the Lite API doesn't allow to search in all of WOS collections unfortunately. I'm currently trying to understand which collection is searched, I'll update the README asap on this.

**Comment by swood-ecology** [comment]
Is there any possibility to interface with the full API for those who have access to the full WOS through their institutions?

**Comment by juba** [comment]
Well, yes, it should be possible. The problem is that I don't have access to it myself, so it's a bit complicated to develop against the full API without being able to test...

**Comment by juba** [comment]
Ok, so it seems that the only available collections with the lite API are "SCI", "ISTP", "ISSHP", and "IC". The full WOS collections list can be found here : 

http://ipscience-help.thomsonreuters.com/wosWebServicesLite/dbEditionsOptionsGroup/databaseEditionsWos.html

By default, searches will now use these four collections, but you can narrow your search with the new `editions` argument to the `wos_search` function (see README).

**Comment by swood-ecology** [comment]
Let me know if you have any code you want me to test.

**Comment by swood-ecology** [comment]
Any thoughts on why I'd get about 5000 fewer hits searching "soil health" in their web platform vs. `wos_search(sid, 'TS="soil quality"')`? I'd think given the greater number of collections on the web platform that I'd get more, not less.

**Comment by juba** [comment]
Are you sure you're using the same queries ? You speak of "soil health" and "soil quality"...

I don't see any differences in number of results here.

**Comment by juba** [comment]
I just took a look at full WOS API. It's too different from the lite one to be able to implement it blindly, without being able to test directly.

I know that my institution is looking for a full API access. When it's done I'll certainly try to add it to `rwos`...
