### ISSUE TITLE
Not authorized for product: WWS

### ISSUE THREAD

**Issue by ghost** [juba/rwos#2]
The package would help me a lot. Unfortunately, I get a error message

    library(rwos)
    sid <- wos_authenticate()

    wos_search(sid, "AU=Wickham Hadley")
    Error in wos_search(sid, "AU=Wickham Hadley") : 
      Error : Not authorized for product: WWS
 
    wos_search(sid, "AU=Wickham Hadley", api = "premium")
    Error in wos_search(sid, "AU=Wickham Hadley", api = "premium") : 
      Error : Error reading XMLStreamReader.

Best wishes
Christof

**Comment by juba** [comment]
Hi,

I can't reproduce your problem, but I wonder if it is not a "subscription" problem. When I try to use `rwos` at work, it works ok. At home, I get an error message with `wos_authenticate()` :

```
Authentication error : No matches returned for IP X.X.X.X
```

So when I see your error message, It seems that your IP is recognized for authentication, but not for access to the WWS service...

**Comment by ramiromagno** [comment]
I am having the same problem.

```R
library(wosr)
sid <- auth(username = NULL, password = NULL)
query <- 'TS = ("animal welfare") AND PY = (2002-2003)'
query_wos(query, sid = sid)
#> Error: Not authorized for product: WWS
```
I am running this code from within my institutional network.

**Comment by juba** [comment]
Unfortunately, I don't think I can do anything about it. 

From the message you get, you seem able to authenticate against the service, but fail to access WWS.

**Comment by ramiromagno** [comment]
Ok @juba, thank you. If I may leave a suggestion here, you could perhaps intercept this error message and return another one hinting towards the lack of access to the WWS service. Before this error I didn't even know that the access to the Web of Science had difference access levels, and that the API level (WWS) access was paid separately...

**Comment by juba** [comment]
Yes, you're totally right, but unfortunately this package is really more of an alpha version. I built it quickly for someone else, and never really used it myself, so I don't think I'll find the time to improve it. Plus, the different WoS services are quite complicated and not something I'll be very keen on wrapping my head around. 

But if someone wants to take it over, the code (which has nothing special) is freely available.

I should put a note in the README to make the package status clearer.

Thanks for taking the time to reporting your issue, and sorry for not being able or willing to do more.

**Comment by kongdd** [comment]
faced with the same problem

**Comment by pzhaonet** [comment]
faced with the same problem
