### ISSUE TITLE
Authentication error : No matches returned for IP X.X.X.X

### ISSUE THREAD

**Issue by nmuggleton** [juba/rwos#4]
I'm trying to run a Web of Science search, but get the following error:

`library(rwos)`
`sid <- wos_authenticate()`
`Error in wos_authenticate() :`
`Authentication error : No matches returned for IP X.X.X.X`

I see [here](https://github.com/juba/rwos/issues/2) that you had the same problem. Did you find a workaround?

Cheers,
Naomi

**Comment by juba** [comment]
I think kind of error is due to the fact that the WoS API is not open. This authentication error means that you are trying to access it from an IP address that doesn't have the right to do so.
