### ISSUE TITLE
Username authentication

### ISSUE THREAD

**Issue by theogrost** [juba/rwos#5]
Hi,
I get:
`Authentication error : No matches returned for Username XXX`
I use my login credentials, that works fine on login.webofknowledge.com. What may be the reason for that?
All the best! :)

**Comment by juba** [comment]
Honestly (and unfortunately), it is very difficult for me to debug this kind of problem...

The package only uses the Lite API. Maybe your credentials are for another kind of subscription ? Does it work without any credentials ?
