### ISSUE TITLE
Request to parse search for 100K+ returns

### ISSUE THREAD

**Issue by sheilasaia** [juba/rwos#6]
Thank you so much for developing this very helpful package! I'm submitting this issue to request that a feature be added to the `wos_search()` function. Specifically, I was hoping to parse the full search into sections when the result is larger than 100K returns (the max limit by the WOS API). I tried to do this by resetting the `$results` value to a smaller number but this resulted in overlapping returns since I could not specify the starting `$results` value. As an alternative approach, I tried parsing the results for searches that are less than 100K entries by setting the `first` and `count` parameters in `wos_retrieve()`. However, I'm getting an error (see below) when trying to set `first = 100001`.

Sample code:
`phos_result <- wos_search(sid, "TS='phosphate' AND DT = Article", editions = c("SCI")) # this runs fine`

`phos_pubs_raw_100kto200k <- wos_retrieve(phos_result, first = 100001, count = 200000) # this gives the error below`

Error: 
"Error in wos_retrieve_page(result, first = indices[i], count = counts[i]) : 
  Error : (IIE0022) The SOAP request message is invalid. Reason: Error received from a server supporting the Web service. Cause: The following input is invalid [Start value cannot exceed 100000]. Remedy: Correct your request and submit it again."

**Comment by juba** [comment]
Hi,

Unfortunately I never used and don't really maintain this package anymore...

Regarding your issue, I think it may not be related to `rwos` but rather to the API. As there is a fixed maximum number of 100k results, the error message you get seems quite logical : you can't ask for results starting after the 100 000th one.

So I don't think I could really help you on this, unfortunately...

**Comment by sheilasaia** [comment]
@juba Ahh I see now. Ok, thank you very much for getting back to me. I'll close this issue.
